# Generated by Django 3.2 on 2022-11-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='sport',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
